version: '2'
services:
   fm-db:
     dockerfile: db.docker
     container-name: fm-mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
       MYSQL_DATABASE: ${DB_DATABASE}
       MYSQL_USER: ${DB_USER}
       MYSQL_PASSWORD: ${DB_PASSWORD}
  fm-web:
    dockerfile: web.docker
    depends-on:
      - fm-db
    container-name: fm-web
    restart: always
    environment:
       MYSQL_HOST: fm-db:3306
       MYSQL_DATABASE: ${DB_DATABASE}
       MYSQL_USER: ${DB_USER}
       MYSQL_PASSWORD: ${DB_PASSWORD}


