version: '3.8'
services:
  fm-db:
    build:
      context: .
      dockerfile: db.docker
    container_name: fm-db
    restart: on-failure
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
  fm-web:
    build:
      context: .
      dockerfile: web.docker
    depends_on:
      - fm-db
    ports:
      - "8080:80"
    container_name: fm-web
    restart: on-failure
    volumes:
      - "./web/:/var/www/html/"

    environment:
      - MYSQL_HOST=fm-db
      - MYSQL_PORT=${DB_PORT}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}