name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      working-directory: web
      php: 7.4
      composer: 2

    steps:
    - uses: actions/checkout@v2

    - name: Validate dependencies
      uses: php-actions/composer@v5
      with:
        php_version: ${{env.php}}
        version: ${{env.composer}}
        working_dir: ${{env.working-directory}}
        command: validate

    - name: Validate dependencies
      uses: php-actions/composer@v5
      with:
        php_version: ${{env.php}}
        version: ${{env.composer}}
        working_dir: ${{env.working-directory}}
        command: install

    - name: Validate dependencies
      uses: php-actions/composer@v5
      with:
        php_version: ${{env.php}}
        version: ${{env.composer}}
        working_dir: ${{env.working-directory}}
        command: test
