name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      working-directory: web

    steps:
    - uses: actions/checkout@v2

    - name: Validate dependencies
      uses: php-actions/composer@v5
      with:
        php_version: 7.4
        version: 2
        working_dir: ${{env.working-directory}}
        command: validate
